### ISSUE TITLE
Criar uma tabela "restaurante_cliente" com campo avaliação

### ISSUE THREAD

**Issue by igorluppi** [Linr-app/linr-backend#6]
Deve conter:
- avaliação int 
- id_usuario foreign key
- id_restaurante foreign key

-------------------
GET /restaurantes/:id -> retorna media das avaliacoes junto
POST /restaurantes/:id/avaliacao -> cria uma nova avaliacao
PUT /restaurantes/:id/avaliacao -> atualiza a avaliacao

os sql:
1)
   insert into restaurante_cliente values ($avaliacao, $id_user, $id_restaurante)

2)
update restaurante_cliente 
set avaliação = $avaliaçao
where id_usuario = $id_user and id_restaurante = $id_restaurante
 
3)
//Criar o seguinte select para aparece na página '**restaurante**'
select avg(avaliacao)
from restaurante_cliente
where id_restaurante = $1;

**Comment by ivandardi** [comment]
Consertado pelo PR #7
